theme="onedark"

[editor]
cursorline=true
scroll-lines=1
line-number="relative"
mouse=false
true-color=true
color-modes=true
auto-pairs=true
auto-save=false
completion-trigger-len=1
rulers=[120]
idle-timeout=50


[editor.cursor-shape]
insert="bar"
normal="block"
select="underline"

[editor.file-picker]
hidden=false

[keys.insert]
"C-["="normal_mode"

[keys.select]
"C-["="normal_mode"

[editor.lsp]
display-messages=true
display-inlay-hints=true

[editor.statusline]
left=["mode", "spinner", "file-name", "file-type", "total-line-numbers", "file-encoding"]
center=[]
right=["selections", "primary-selection-length", "position", "position-percentage", "spacer", "diagnostics", "workspace-diagnostics", "version-control"]